detectors:
  LongParameterList:
    max_params: 6
  UnusedParameters:
    exclude:
      - "FakeTwilio#create"
  DuplicateMethodCall:
    max_calls: 3
    exclude:
      - "RestaurantInvitationsController#update"
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  RepeatedConditional:
    max_ifs: 3
  ControlParameter:
    exclude:
    - "Purchase#purchase_pack_quantity_changed"
    - "StatisticsController#separate_by_step"
    - "Restaurants::StatisticsController#separate_by_days"
  TooManyStatements:
    max_statements: 12
    exclude:
      - "RestaurantInvitationsController#update"
  UtilityFunction:
    public_methods_only: true
    exclude:
      - "ApplicationController#default_url_options"
      - "Ability#restaurant_user_abilities"
      - "scoped_collection"

exclude_paths:
  - db/migrate
  - vendor/bundle
