detectors:
  DuplicateMethodCall:
    max_calls: 3
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  RepeatedConditional:
    max_ifs: 3
  TooManyStatements:
    max_statements: 10
  UtilityFunction:
    public_methods_only: true
    exclude:
      - "ApplicationController#default_url_options"

exclude_paths:
  - db/migrate
  - vendor/bundle
